//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teradata
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee12345
    {
        public employee12345()
        {
            this.enter = new HashSet<enter>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string phone_number { get; set; }
        public string login { get; set; }
        public string emp_password { get; set; }
    
        public virtual ICollection<enter> enter { get; set; }
    }
}
