//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teradata
{
    using System;
    using System.Collections.Generic;
    
    public partial class enter
    {
        public int id_enter { get; set; }
        public Nullable<int> id { get; set; }
        public string date_enter { get; set; }
    
        public virtual employee12345 employee12345 { get; set; }
    }
}
